spring:
#  h2 console enabled
  h2:
    console:
      enabled: true
#  h2 db info
  datasource:
    url: jdbc:h2:mem:testdb
#  jpa sql show and auto update table
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
